# Antes del repaso en Python
Los siguientes ejercicios permitirán comprobar el conocimiento básico en Python.

Si no recuerda algún concepto o quiere profundizar recomiendo revisar **W3 schools**:
* Python https://www.w3schools.com/python/
* Numpy  https://www.w3schools.com/python/numpy/
* Pandas https://www.w3schools.com/python/pandas/

## Ejercicio 1

Escriba una función que encuentre todos los numeros que son divisibles por $7$ pero no son un multiplo de $5$ entre un rango especificado por parámetro (ambos números seben incluirse).  Esta función retorna una lista.

**Ayuda:**
Considere el uso de la función `range()`

In [ ]:
def function_numbers(begin, end):
    numbers = []
    for num in range(begin, end + 1):
        if num % 7 == 0 and num % 5 != 0:
            numbers.append(num)
    return numbers
print(function_numbers(2,50))

[7, 14, 21, 28, 42, 49]


In [ ]:
"""
Se inicializa una lista vacía llamada numbers.
Se utiliza un bucle for que itera sobre el rango de números desde begin hasta end (ambos inclusive).
Para cada número en el rango, se verifica si es divisible por 7 (num % 7 == 0) y no es múltiplo de 5 (num % 5 != 0).
Si ambas condiciones se cumplen, el número se añade a la lista numbers.
Finalmente, la función retorna la lista numbers.
"""


## Ejercicio 2

Dado un numero $n$, escriba una función que retorne un diccionario que contenga $(i,i*i)$, donde $i$ es un numero entero entre $1$ y $n$ ( ambos se incluyen ).

In [ ]:
def function_dictionary(n):
    dictionary = {}
    for i in range(1, n + 1):
        dictionary[i] = i * i
    return dictionary
print(function_dictionary(10))

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


Se inicializa un diccionario vacío llamado dictionary.
Se utiliza un bucle for que itera sobre el rango de números desde 1 hasta
𝑛
n (ambos inclusive).
Para cada número
𝑖
i en el rango, se añade una entrada al diccionario donde la clave es
𝑖
i y el valor es
𝑖
×
𝑖
i×i.
Finalmente, la función retorna el diccionario.

## Ejercicio 3

Escriba una función que calcule un valor según una formula dada:

$Q = \sqrt{ \frac{2*C*D}{H} }$

$C$ es un número entero.

$H$ es un número entero.

$D$ es una lista numeros pueden ser enteros y decimales.

La función debe de retornar el valor de $Q$ para cada uno de los valores $D$ definidos en la lista, devuelve una lista de solo enteros.

In [ ]:
import math

def function_formula(c, h, d_list):
    results = []
    for d in d_list:
        q = math.sqrt((2 * c * d) / h)
        results.append(int(q))
    return results

In [ ]:
C = 50
H = 30
D = [100,150.5,180]

print(function_formula(C, H, D))

[18, 22, 24]


Se importa el módulo math para usar la función math.sqrt que calcula la raíz cuadrada.
Se inicializa una lista vacía llamada results para almacenar los resultados.
Se itera sobre cada valor
𝑑
d en d_list.
Para cada
𝑑
d, se calcula el valor de
𝑄
Q usando la fórmula dada.
El valor de
𝑄
Q se convierte a un entero usando int() y se agrega a la lista results.
Finalmente, la función retorna la lista results.

## Ejercicio 4

Escribe una función que tome 2 digitos $X$ y $Y$ como una entrada para generar una matriz de $X$ filas y $Y$ columnas. Cada uno de los elementos en la matriz será la multiplicación del número de la fila por el número de la columna, la función retorna un `numpy.array`.

In [ ]:
import numpy as np

def function_array(x, y):
    array = np.zeros((x, y))

    for i in range(x):
        for j in range(y):
            array[i, j] = i * j

    return array

In [ ]:
print(function_array(3, 5))
print(type(function_array(3, 5)))

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]
<class 'numpy.ndarray'>


**Deberia de tener el siguiente resultado:**
```
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]
<class 'numpy.ndarray'>
```

## Ejercicio 5

Escribir una función que ordene tuplas (nombre, edad, estatura) de manera ascendente. Como parametro de entrada tiene la lista de tuplas y un numero que indica por que valor desea ordenar.  El criterio para ordenar es:

1. Ordenar por nombre ( recibe 0 )
2. Ordenar por edad ( recibe 1 )
3. Ordenar por estatura ( recibe 2 )

In [ ]:
def function_sorter(tuples_list, pos):
    sorted_list = sorted(tuples_list, key=lambda x: x[pos])
    # CODE HERE
    return sorted_list

In [ ]:
tuplas = [('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]

print(function_sorter(tuplas, 0))
print(function_sorter(tuplas, 1))
print(function_sorter(tuplas, 2))

[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]
[('Jony', '17', '91'), ('Jony', '17', '93'), ('Tom', '19', '80'), ('John', '20', '90'), ('Json', '21', '85')]
[('Tom', '19', '80'), ('Json', '21', '85'), ('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93')]


**Deberia de tener el siguiente resultado:**
```
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]
[('Jony', '17', '91'), ('Jony', '17', '93'), ('Tom', '19', '80'), ('John', '20', '90'), ('Json', '21', '85')]
[('Tom', '19', '80'), ('Json', '21', '85'), ('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93')]
```

In [ ]:
def function_sorter(tuples_list, pos):
    sorted_list = None
    # CODE HERE
    return sorted_list